services:
  - type: web
    name: wanderlust
    env: docker
    region: oregon
    plan: starter
    branch: main
    healthCheckPath: /health
    envVars:
      - key: FLASK_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
    autoDeploy: true 